### ISSUE TITLE
error in PreLollipopDetector

### ISSUE THREAD

**Issue by nczoltan** [ricvalerio/foregroundappchecker#1]
Hi!

First of all, thank you for your effort. The Library is good. And it will be better if you can fix the bugs below:

The PreLollipopDetector wont work. First of all, the <uses-permission android:name="android.permission.GET_TASKS" /> must be declared in manifest, else activityManager.getRunningTasks(1) will throw a SecurityException.

Second error:
Still in the PreLollipopDetector.java. You have to assign the foregroundAppPackageInfo.applicationInfo.loadLabel(pm).toString() to the foreGroundApp variable else the method will be always return null.

Best Regards!

Zoltan

**Comment by ricvalerio** [comment]
Hi!

Thank you, I am happy it's helpful! And thank you very much for the report, completely forgot to add that needed permission to the documentation, and will also fix the other bug. I can only pick this on Monday though,, sorry for the delay.

Cheers
