### ISSUE TITLE
Just a thank you

### ISSUE THREAD

**Issue by swa00** [ricvalerio/foregroundappchecker#3]
for  your great work :-)

**Comment by ricvalerio** [comment]
Thank you very much, I really appreciate it! :-) Let me know if you have any problems or have any requests.

Cheers!

**Comment by swa00** [comment]
Yes Ric - only  one  small problem 

all works  fine, but  under 5.1 i do  not  get any callback.
Do  you have  any  idea ???

Steva

**Comment by ricvalerio** [comment]
Hello!

Are you using version 1.0.1?

**Comment by swa00** [comment]
Whoops,  you are  online :-) *shocked* :-)

yes  the  newest,
(but  implemented as  source,  not  via  gradle)

**Comment by ricvalerio** [comment]
You got me in the right time. :-) Let me take a look at it, I will get back at you in a moment.

**Comment by swa00** [comment]
*Coffetime* :-)
no  hurry  take  time , i will  be  awake :-)

**Comment by ricvalerio** [comment]
It's working for me the sample in the latest version. Is it a specific app that it's not detecting? Did you add the necessary permission GET_TASKS?

**Comment by swa00** [comment]
Arrrhgh  -  wait  
(i  did  not pay  attation on this  , because it  works  on 4.x)

**Comment by swa00** [comment]
i'm  sorry  ,  no result..
 mAppChecker
                .other(new AppChecker.Listener()
                {
                    @Override
                    public void onForeground(String packageName)
                    {
                        if ( packageName != null)
                        {
                            Log.d ("_ITE"," Package in Foreground : " + packageName);


Works  fine under Marshmellow, 4.x  but  not  with 5.1
  <uses-permission android:name="android.permission.GET_TASKS" />
    <uses-permission android:name="android.permission.PACKAGE_USAGE_STATS" tools:ignore="ProtectedPermissions" />

**Comment by swa00** [comment]
P.S  GET_TASK  is  signed as deprectated
MinSDK  in my  Project 17

**Comment by swa00** [comment]
Ric, i'm sorry -  let  me  explain

i did not enabled the USAGE_ACCESS_SETTINGS  under 5.1

i allways  was  on the  way  , that  this  is  ONLY  necessary under 6.x

After requesting the ACTION_USAGE_ACCESS_SETTING  also  under 5.1 it works  fine

I'AM SOOOOOOOOOOOOOOO  SORRY  for  the  confusion and  thank  you  for  your  time

Shame on me :-( ^^

**Comment by ricvalerio** [comment]
No worries, cheers that it's working! I'm happy to be of help in any case. :-)
