### ISSUE TITLE
appChecker.getForegroundApp() error

### ISSUE THREAD

**Issue by renatosc** [ricvalerio/foregroundappchecker#4]
When trying to run your code example:
```
AppChecker appChecker = new AppChecker();
String packageName = appChecker.getForegroundApp();

```
I get the error:

```
Error:(54, 40) error: method getForegroundApp in class AppChecker cannot be applied to given types;
required: Context
found: no arguments
reason: actual and formal argument lists differ in length
```

**Comment by ricvalerio** [comment]
Oops, that is wrong documentation right there, my apologies.

Please pass context as parameter, as hinted by the error message:

AppChecker appChecker = new AppChecker();
String packageName = appChecker.getForegroundApp(context);

Sorry for that. Potentially might make so we pass it in AppChecker constructor or a set method, as to void to having to pass the context whenever we want to get the foreground app package name.

Ricardo

**Comment by ricvalerio** [comment]
Corrected documentation to reflect the current api.

Thanks for the report!

Ricardo
