### ISSUE TITLE
java.lang.NullPointerException 

### ISSUE THREAD

**Issue by rajnishmishra20** [ricvalerio/foregroundappchecker#7]
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List java.util.concurrent.ScheduledExecutorService.shutdownNow()' on a null object reference
       at com.rvalerio.fgchecker.AppChecker.stop(SourceFile:66)

**Comment by ricvalerio** [comment]
Hi rajnishmishra20,

Thanks for the report. A fix was issued in the new version.

Let me know if happens again or you have any other issue or question.

Cheers,
Ricardo
